### ISSUE TITLE
plus-microstate / toolbox

### ISSUE THREAD

**Issue by wangguangjun99** [plus-microstate/toolbox#9]
Hi
In tutorial 4， When the following code is run, an error will be reported：
coh = coh.cluster_globalmaps2individual([],true) ; % 2nd input is true to keep polarity

error microstate.individual/cluster_get_gfppeaks (line 39)
    [~,peaks] = findpeaks(obj.gfp) ; % peaks of gfp

error microstate.individual/cluster_alignmaps (line 52)
        [xpeak,~,peak2sample] = obj.cluster_get_gfppeaks ; %
        calculate GFP peaks

error microstate.cohort/cluster_globalmaps2individual (line 20)
   obj.individual(i) =
    obj.individual(i).cluster_alignmaps([],'keep_polarity',keep_polarity)
; % get labels

**Comment by lukewtait** [comment]
Hi Wang, 

We have solved this issue this over email, but I'm posting the solution here in case anyone else has this issue. 

The issue above was caused because EEGLab was also on the Matlab path. EEGLab contains a function called `findpeaks` which is different from the `findpeaks` function in Matlab's signal processing toolbox. Since Matlab's `findpeaks` is used in our code, but EEGLab's version was being called, this caused an error. 

You can check that this is what is causing the issue by typing `which("findpeaks")` into the Matlab console. If the output contains reference to EEGLab, then the code will call the EEGLab version of the function. For the code to work, the output should read something like `~/MATLAB_R2021a/toolbox/signal/signal/findpeaks`.

The solution is to either open a new instance of Matlab without running EEGLab, or by removing the EEGLab `findpeaks` by calling `rmpath(fileparts(which("findpeaks")))`

Thanks, 
Luke

**Comment by wangguangjun99** [comment]
Hi  Luke

Thank you very much
Best regards
Wang GJ

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Luke ***@***.***>
发送时间: 2022年8月17日 22:44
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [plus-microstate/toolbox] plus-microstate / toolbox (Issue #9)


Hi Wang,

We have solved this issue this over email, but I'm posting the solution here in case anyone else has this issue.

The issue above was caused because EEGLab was also on the Matlab path. EEGLab contains a function called findpeaks which is different from the findpeaks function in Matlab's signal processing toolbox. Since Matlab's findpeaks is used in our code, but EEGLab's version was being called, this caused an error.

You can check that this is what is causing the issue by typing which("findpeaks") into the Matlab console. If the output contains reference to EEGLab, then the code will call the EEGLab version of the function. For the code to work, the output should read something like ~/MATLAB_R2021a/toolbox/signal/signal/findpeaks.

The solution is to either open a new instance of Matlab without running EEGLab, or by removing the EEGLab findpeaks by calling rmpath(fileparts(which("findpeaks")))

Thanks,
Luke

―
